#!/bin/bash

if ! command -v kind &> /dev/null; then
    echo "KinD not found. Please install KinD."
    exit 1
fi

some_text="# This manifest was generated by flux. DO NOT EDIT."
clusters_path="$(readlink -f "$0" | awk -F'scripts/clean.sh' '{print $1}')"
clusters=$(ls "${clusters_path}clusters/" | xargs -n 1 basename | tr '\n' ' ')
for cluster in ${clusters}; do
    echo "-------------------------------------------"
    echo "Cluster: ${cluster}"
    kind delete cluster --name="$cluster"
    echo -e "${some_text}" > "${clusters_path}clusters/${cluster}/flux-system/gotk-components.yaml"
    echo -e "${some_text}" > "${clusters_path}clusters/${cluster}/flux-system/gotk-sync.yaml"
done

echo "-------------------------------------------"
echo "Don't forget to commit and push the $GITHUB_REPO repository"
