apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.5.3"
  values:
    ingress:
      hosts:
        - host: podinfo.prod
          paths:
            - path: /
              pathType: ImplementationSpecific