clusters:
#  dev:
#    file: "/Users/viktor/.kube/config"
  stage:
    file: "/Users/viktor/.kube/config"



bot:
  admins:
    - "viktorzhabskiy"

repo:
  owner: "ViktorDevOpsCourse"
  name: "flux-image-updates"
  branch: "main"