clusters:
  production:
    file: "./kube.prod"
  staging:
    file: "./kube.stage"

namespaces:
  - "podinfo"

bot:
  admins:
    - "viktorzhabskiy"

repo:
  owner: "ViktorDevOpsCourse"
  name: "flux-image-updates"
  branch: "main"